import type { Prisma } from '../../generated/prisma/client';
import * as z from 'zod';
import { SocialWhereInputObjectSchema as SocialWhereInputObjectSchema } from './objects/SocialWhereInput.schema';
import { SocialOrderByWithAggregationInputObjectSchema as SocialOrderByWithAggregationInputObjectSchema } from './objects/SocialOrderByWithAggregationInput.schema';
import { SocialScalarWhereWithAggregatesInputObjectSchema as SocialScalarWhereWithAggregatesInputObjectSchema } from './objects/SocialScalarWhereWithAggregatesInput.schema';
import { SocialScalarFieldEnumSchema } from './enums/SocialScalarFieldEnum.schema';
import { SocialCountAggregateInputObjectSchema as SocialCountAggregateInputObjectSchema } from './objects/SocialCountAggregateInput.schema';
import { SocialMinAggregateInputObjectSchema as SocialMinAggregateInputObjectSchema } from './objects/SocialMinAggregateInput.schema';
import { SocialMaxAggregateInputObjectSchema as SocialMaxAggregateInputObjectSchema } from './objects/SocialMaxAggregateInput.schema';
import { SocialAvgAggregateInputObjectSchema as SocialAvgAggregateInputObjectSchema } from './objects/SocialAvgAggregateInput.schema';
import { SocialSumAggregateInputObjectSchema as SocialSumAggregateInputObjectSchema } from './objects/SocialSumAggregateInput.schema';

export const SocialGroupBySchema: z.ZodType<Prisma.SocialGroupByArgs> = z.object({ where: SocialWhereInputObjectSchema.optional(), orderBy: z.union([SocialOrderByWithAggregationInputObjectSchema, SocialOrderByWithAggregationInputObjectSchema.array()]).optional(), having: SocialScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(SocialScalarFieldEnumSchema), _count: z.union([ z.literal(true), SocialCountAggregateInputObjectSchema ]).optional(), _min: SocialMinAggregateInputObjectSchema.optional(), _max: SocialMaxAggregateInputObjectSchema.optional(), _avg: SocialAvgAggregateInputObjectSchema.optional(), _sum: SocialSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.SocialGroupByArgs>;

export const SocialGroupByZodSchema = z.object({ where: SocialWhereInputObjectSchema.optional(), orderBy: z.union([SocialOrderByWithAggregationInputObjectSchema, SocialOrderByWithAggregationInputObjectSchema.array()]).optional(), having: SocialScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(SocialScalarFieldEnumSchema), _count: z.union([ z.literal(true), SocialCountAggregateInputObjectSchema ]).optional(), _min: SocialMinAggregateInputObjectSchema.optional(), _max: SocialMaxAggregateInputObjectSchema.optional(), _avg: SocialAvgAggregateInputObjectSchema.optional(), _sum: SocialSumAggregateInputObjectSchema.optional() }).strict();